music/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    url(r'^$',views.home, name = "home"),
    url(r'login/', views.login_user, name = 'login'),
    url(r'^logout/$', views.logout_user, name= "logout"),

    #----------------------------------------------------------------------------
    url(r'^profile/(?P<user_name>\w+)/$', views.profile_user, name= "profile"),
    #---------------------------------------------------------------------------
    url(r'^register/$', views.register_user, name= "register"),
    url(r'^edit_profile/$', views.edit_profile, name = "edit_profile"),
    url(r'^dashbaord/$', views.dashboard, name = "dashboard"),
    
    #Password Change URL............
    url(r'^change_password/$', views.change_password, name = "change_password"),

    #password Reset URLS...........
    path('password_reset/', PasswordResetView.as_view(), name='password_reset' ),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    #Email Confirm URLs.....
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),

    #Contact Us Page ...
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^compania/$', views.compania, name="compania"),
    url(r'^search/$', views.search, name="search"),
    url(r'^search1/$', views.search1, name="search1"),
    url(r'^search2/$', views.search2, name="search2"),
    url(r'^search3/$', views.search3, name="search3"),    
    url(r'^form/$', views.CompañíaView,name='form'),
    url(r'^edit/(?P<id>\d+)/$', views.CompañíaViewEdit, name="edit"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('music.urls')),
]

#handler404 = music.views.handler404
#handler404 = 'music.views.error_404_view'

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

music/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import profileModel,Compañía
from django.contrib.auth import (authenticate, get_user_model, password_validation,)

#User Login Form ................
class loginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())

#User Registration Form...................
class registerForm(forms.ModelForm):
    password = forms.CharField(label = 'Password', widget = forms.PasswordInput(),strip=False,help_text=password_validation.password_validators_help_text_html(),)
    password2 = forms.CharField(label = 'Repeat Password', widget = forms.PasswordInput(),strip=False,help_text="Both Passwords should be same.",)
    email = forms.EmailField(label = 'Email Address', widget = forms.TextInput())
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
        ]

    #Cleaning Method for password Match..........
    def clean_password2(self):
        cd = self.cleaned_data
        if self.cleaned_data.get('password') != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']

    #Cleaning Method for Email Unique..........
    def clean(self):
        if self.cleaned_data.get('email') is None:
            raise ValidationError("Enter a valid E-mail Address")
        varEmail = self.cleaned_data.get('email').lower()
        if User.objects.filter(email = varEmail).count() != 0 :
            if not User.objects.get(email = varEmail).is_active :
                User.objects.get(email = varEmail).delete()
            else:
                raise ValidationError(self.cleaned_data.get('email') + "\tAlready Exists.")
    
#User Can Edit his profile using this Form..........................
class EditProfileForm(UserChangeForm):
    password = forms.CharField(label='', widget = forms.TextInput(attrs = {'type' : 'hidden'}))
    class Meta:
        model = User
        fields = ['username',
                  'first_name',
                  'last_name',
                  'password',
                  ]

#User Extra Information ................
class profileInformForm(forms.ModelForm):
    class Meta:
        model = profileModel
        fields = '__all__'

class contactForm(forms.Form):
    userName =  forms.CharField(label='', widget = forms.TextInput(attrs = {'placeholder' : 'Name'}))    
    email = forms.EmailField(label = '', widget = forms.TextInput(attrs = {'placeholder' : 'Email'}))
    body = forms.CharField(label='', widget=forms.Textarea(attrs = {'placeholder':'Message', 'cols' : '30', 'rows' : '10'}))


class CompañíaForm1(forms.ModelForm):
    class Meta:
        model  = Compañía
        exclude = ['Creado_por']

music/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .forms import loginForm, registerForm, EditProfileForm, profileInformForm, contactForm, CompañíaForm1
from django.contrib import messages
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from .models import profileModel, Compañía
from django.urls import reverse
from django.db.models import Q


def handler404(request):
    return render(request, '404.html', status=404)


def home(request):
    return render(request, 'music/home.html', )


@login_required()
def dashboard(request):
    return render(request, 'music/dashboard.html')


def login_user(request):
    if request.method != 'POST':
        form = loginForm()
    else:
        form = loginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.warning(
                    request, 'Usename or password may have been entered incorrectly.')
                return redirect('login')

    return render(request, 'music/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('login')


@login_required()
def profile_user(request, user_name):
    message = ''
    try:
        user = User.objects.get(username=user_name)
        editProfile = False
        #print(request.user.username == user_name)
        if (request.user == user):
            if request.user.is_superuser:
                contactNumber = None
                editProfile = True
            else:
                contactNumber = profileModel.objects.get(
                    user=user).contactNumber
                editProfile = True
        else:
            if request.user.is_superuser:
                contactNumber = profileModel.objects.get(
                    user=user).contactNumber
                editProfile = False
            else:
                contactNumber = None
                editProfile = None
    except:
        user = request.user
        if request.user.is_superuser:
            contactNumber = None
            editProfile = True
            message = user_name + " Doest Not Exists "
        else:
            contactNumber = profileModel.objects.get(
                user=User.objects.get(username=request.user.username)).contactNumber
            editProfile = True
            message = user_name
    return render(request, 'music/profile.html', {'contactNumber': contactNumber, 'editProfile': editProfile, 'user': user, 'message': message})
    # return render(request, 'music/index-login.html')


def register_user(request):
    if request.method != 'POST':
        form = registerForm()
        form_2 = profileInformForm()
    else:
        form = registerForm(request.POST)
        form_2 = profileInformForm(request.POST)
        if form.is_valid() & form_2.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.set_password(form.cleaned_data['password2'])
            user.email = form.cleaned_data['email'].lower()
            user.save()
            profile = profileModel.objects.create(user=user)
            profile.contactNumber = form_2.cleaned_data['contactNumber']
            profile.save()
            current_site = get_current_site(request)
            message = render_to_string('music/acc_active_email.html', {
                'user': user, 'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            # Sending activation link in terminal
            # user.email_user(subject, message)
            mail_subject = 'Activate your account.'
            #to_email = form.cleaned_data.get('email')
            to_email = form.cleaned_data.get('email').lower()
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            # return HttpResponse('Please confirm your email address to complete the registration.')
            return render(request, 'music/acc_active_email_confirm.html')
    return render(request, 'music/register.html', {'form': form, 'form_2': form_2})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        #login(request, user)
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        return redirect('login')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required()
def edit_profile(request):
    if request.method != 'POST':
        form = EditProfileForm(instance=request.user)
    else:
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            # return redirect('profile', username = request.user.username)
            return HttpResponseRedirect(reverse('profile', args=[request.user.username]))
    return render(request, 'music/edit_profile.html', {'form': form})


@login_required()
def change_password(request):
    if request.method != 'POST':
        form = PasswordChangeForm(user=request.user)
    else:
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(reverse('profile', args=[request.user.username]))
    return render(request, 'music/change_password.html', {'form': form})


# -----------------------
def contact(request):
    if request.method != 'POST':
        form = contactForm()
    else:
        form = contactForm(request.POST)
        if form.is_valid():
            mail_subject = 'Contact -- By -- ' + \
                form.cleaned_data.get('userName')
            to_email = settings.EMAIL_HOST_USER
            message = form.cleaned_data.get('body')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return redirect('home')

    context = {'form': form}
    return render(request, 'music/contact.html', context)


def CompañíaView(request):
    form1 = CompañíaForm1()

    if request.method == 'POST':
        form1 = CompañíaForm1(request.POST)

        if form1.is_valid():
            new = form1.save(commit=False)
            new.Creado_por = request.user
            form1.save()

            return redirect('compania')
    context = {
        'form1': form1,

    }
    return render(request, 'music/form.html', context)


def search(request):
    query = request.GET.get('query', None)
    company = Compañía.objects.all()
    if query is not None:
        company = company.filter(
            Q(Nombre__icontains=query) 
        )
    print(query)
    print(company)
    context = {

        'obj': company,
        'query': query
    }

    return render(request, 'music/compania.html', context)


def search1(request):
    query = request.GET.get('query', None)
    company = Compañía.objects.all()
    if query is not None:
        company = company.filter(

            Q(Código_de_Compañía_OWM__icontains=query)

        )
    context = {

        'obj': company,
        'query': query
    }

    return render(request, 'music/compania.html', context)


def search2(request):
    query = request.GET.get('query', None)
    company = Compañía.objects.all()
    if query is not None:
        company = company.filter(

            Q(Código_de_Compañía_Emisora__icontains=query)

        )
    context = {

        'obj': company,
        'query': query
    }

    return render(request, 'music/compania.html', context)

def search3(request):
    query = request.GET.get('query', None)
    company = Compañía.objects.all()
    if query is not None:
        company = company.filter(

            Q(RUT__icontains=query)

        )
    context = {

        'obj': company,
        'query': query
    }

    return render(request, 'music/compania.html', context)


def compania(request):
    obj = Compañía.objects.all()
    return render(request, 'music/compania.html', {'obj': obj})


def CompañíaViewEdit(request, id):
    obj = Compañía.objects.get(id=id)
    form1 = CompañíaForm1(instance=obj)
    if request.method == 'POST':
        form1 = CompañíaForm1(request.POST, instance=obj)
        if form1.is_valid():
            new = form1.save(commit=False)
            new.Creado_por = request.user
            form1.save()
            return redirect('compania')
    context = {
        'form1': form1,
        'obj': obj,
    }
    return render(request, 'music/formedit.html', context)

music/templates/music/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

music/templates/music/acc_active_email_confirm.html
{% extends "Base.html" %}
{% load static %}
{% block title %}Email Verification{% endblock %}







{% block register %}
<div class="register-login-area">
                            
        <a href="{% url 'register' %}" class="btn active">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endblock  %}




{% block content %}
  
    <div class="container" style="margin-top: 150px;">
      <div class="alert alert-info">
        <strong><h1>Email Verification</h1></strong><p>Please confirm your email address to complete the registration. </p>
      </div>
      
    </div>
{% endblock content %}

music/templates/music/acc_active_sent.html
{% extends "Base.html" %}
{% load static %}
{% block title %}Email Verification{% endblock %}

{% block register %}
<div class="register-login-area">
                            
        <a href="{% url 'register' %}" class="btn active">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endblock  %}



{% block content %}
    <link rel="stylesheet" type = "text/css" href="{% static 'music/css/StyleSheet3.css' %}">

    <div class="container" style="margin-top: 150px;">
      <div class="alert alert-info">
        <strong><h1>Email Verification</h1></strong><p>Please confirm your email address to complete the registration. </p>
      </div>
      
    </div>
{% endblock content %}

music/templates/music/change_password.html
{% extends "Base.html" %}
{% load static %}
{% block title %}Change Password{% endblock %}
{% block content %}

        <div class="container">
            <center>
            <div class="card" style="width:18rem;">
                <div class="card-header">
                            Change Password
                    </div>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger alert-dismissible">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="card-body">

                
                <form action="{% url 'change_password' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class = "exampleInputPassword1">Old Password </label>
                        <input type="password" name="old_password" autofocus required id="id_old_password"  class="form-control"  placeholder="Enter Old Password">
                    <div>
                        <br>
                    <div class="form-group">
                        <label class = "exampleInputPassword2">New Password</label>
                        <input type="password" name="new_password1" required id="id_new_password1"  class="form-control"  placeholder="Enter New Password">
                        <small id="passwordHelpInline" class="text-muted">
                                <ul>
                                    <li>Your password can&#39;t be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can&#39;t be a commonly used password.</li>
                                    <li>Your password can&#39;t be entirely numeric.</li>
                                </ul>
                        </small>
                    <div>
                        <br>
                            <div class="form-group">
                                    <label class = "exampleInputPassword3">Confirm New Password</label>
                                    <input type="password" name="new_password2" required id="id_new_password2"  class="form-control"  placeholder="Enter New Confirm Password">
                                <div>
                        <br>
                    <button type="submit" class="btn btn-primary" value="Change Password">Change Password</button>
                    
                </form>
            </div>
            </div>

        </center>
        </div>
{% endblock content %}

music/templates/music/contact.html
{% extends 'Base.html' %}
{% load static %}
{% block title %} Contact {% endblock %}




{% block register %}
{% if request.user.is_authenticated %}
    <div class="register-login-area">
                                
            <a href="{% url 'profile' request.user.username  %}" class="btn">{{ request.user.username}}</a>
            <a href="{% url 'logout' %}" class="btn">Logout</a>
        
        </div>

{% else %}

<div class="register-login-area">
                                
        <a href="{% url 'register' %}" class="btn">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endif %}

    {% endblock  %}






{% block content %}

<br>
<br>
<br>
<br>

    <!-- ##### Contact Area Start ##### -->
    <section class="contact-area">
        <div class="container">
            <div class="row">
                <!-- Contact Info -->
                <div class="col-12 col-lg-6">
                    <div class="contact--info mt-50 mb-100">
                        <h4>Contact Info</h4>
                        <ul class="contact-list">
                            <li>
                                <h6><i class="fa fa-clock-o" aria-hidden="true"></i> Business Hours</h6>
                                <h6>8:00 AM - 4:00 PM</h6>
                            </li>
                            <li>
                                <h6><i class="fa fa-phone" aria-hidden="true"></i> Number</h6>
                                <h6>+92331-4307703</h6>
                            </li>
                            <li>
                                <h6><i class="fa fa-envelope" aria-hidden="true"></i> Email</h6>
                                <h6>info@alum.com</h6>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Contact Form -->
                <div class="col-12 col-lg-6">
                    <div class="contact-form">
                        <h4>Get In Touch</h4>
                        
                        <form action="{% url 'contact' %}" method="post">
                            {% csrf_token %}

                            
                            <div class="row">
                                <div class="col-12 col-lg-6">
                                    <div class="form-group">
                                        <input type="text" name="userName" placeholder="Name" required id="id_userName" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6">
                                    <div class="form-group">
                                        <input type="text" name="email" placeholder="Email" required id="id_email" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <textarea name="body" class="form-control" cols="30" rows="10" placeholder="Message" required id="id_body"></textarea>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn clever-btn w-100">Send</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->


{% endblock %}

music/templates/music/dashboard.html
{% extends "Base.html" %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <link rel="stylesheet" type = "text/css" href="{% static 'music/css/StyleSheet3.css' %}">
    <br>
    <br>
    <br>
    <br>  
    <h1>Welcome to the dashboard</h1>
{% endblock content %}

music/templates/music/home.html
{% extends 'Base.html' %}
{% load static %}
{% block title %} ALUM {% endblock %}



{% block register %}

{% if request.user.is_authenticated  %}
<div class="register-login-area">




    <a href="{% url 'profile' request.user.username  %}" class="btn">{{ request.user.username }}</a>
    <a href="{% url 'logout' %}" class="btn">logout</a>

</div>
{% else %}
<div class="register-login-area">
    <a href="{% url 'login' %}" class="btn">Login</a>
</div>
{% endif %}
{% endblock  %}

{% block content %}
{% if request.user.is_authenticated  %}
<div class="register-login-area">


    <br>

   <h5>Hi   {{ request.user.username }}!<br>
    <a href="{% url 'logout' %}" class="btn">logout</a>
</h5> 
</div>
{% else %}
<div class="register-login-area">
    <a href="{% url 'login' %}" class="btn">Login</a>
</div>
{% endif %}
{% endblock %}

music/templates/music/register.html
{% extends "Base.html" %}
{% load static %}
{% block title %}Registration{% endblock %}



    {% block register %}
    <div class="register-login-area">
                                
            <a href="{% url 'register' %}" class="btn active">Register</a>
            <a href="{% url 'login' %}" class="btn">Login</a>
        
        </div>
    {% endblock  %}

    {% block content %}

    <style>
     input::-webkit-inner-spin-button, input::-webkit-outer-spin-button{ -webkit-appearance:none; } input[type="number"]{ -moz-appearance:textfield; }
    </style>
    <br>
    <div class="container">
        <center>
            <div class="card" style="width: 22rem;">
                    <div class="card-header text-center">
                            Registration Form
                    </div>
                          {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger alert-dismissible">
                                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}

                            {% if form_2.errors %}
                            {% for field in form_2 %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger alert-dismissible">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
            
                    
                    <div class="card-body">
                            <form action="{% url 'register' %}" method="POST">
                                    {% csrf_token %}
                                    <div  class="form-group">
                                        <label for="id_username" >Username</label>
                                        <input type="text" name="username" maxlength="150" required id="id_username" class="form-control"  placeholder="Enter User">
                                        <small id="usernameHelpInline" class="text-muted">
                                                Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                                              </small>
                                    </div>

                                    <div class="form-group">
                                            <label for="id_first_name">First name</label>
                                            <input type="text" name="first_name" maxlength="30" id="id_first_name" class="form-control"  placeholder="Enter First Name">
                                    </div>
                                    
                                    <div class="form-group">
                                            <label for="id_last_name">Last name</label>
                                            <input type="text" name="last_name" maxlength="150" id="id_last_name" class="form-control"  placeholder="Enter Last Name">
                                    </div>

                                    <div class="form-group">
                                            <label for="id_password">Password</label>
                                            <input type="password" name="password" required id="id_password" class="form-control"  placeholder="Enter Password">
                                            <small id="passwordHelpInline" class="text-muted">
                                                    <ul>
                                                        <li>Your password can&#39;t be too similar to your other personal information.</li>
                                                        <li>Your password must contain at least 8 characters.</li>
                                                        <li>Your password can&#39;t be a commonly used password.</li>
                                                        <li>Your password can&#39;t be entirely numeric.</li>
                                                    </ul>
                                            </small>
                                    </div>

                                    <div class="form-group">
                                            <label for="id_password2">Confirm Password</label>
                                            <input type="password" name="password2" required id="id_password2" class="form-control"  placeholder="Enter Confirm Password">
                                            <small id="passwordHelpInline" class="text-muted">
                                                    Both Passwords should be same.
                                            </small>
                                    </div>

                                    <div class="form-group">
                                            <label for="id_email">Email Address</label>
                                            <input type="text" name="email" required id="id_email" class="form-control"  placeholder="Enter Email">
                                            
                                    </div>

                                    <div class="form-group">
                                            <label for="id_contactNumber">Contac tNumber</label>
                                            <input type="number" name="contactNumber" id="id_contactNumber"  class="form-control"  placeholder="Enter Contact Number">
                                    </div>
                                    <center>
                                            <button type="submit" class="btn btn-primary" value="Sign-Up">Get Register</button>
                                        </center>
                                </form>
                    
                    </div>
            </div>
        
        </center>
        </div>

        <br>
{% endblock content %}